
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'healthcare_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      +materialized: table


sources:
  - name: data_feed
    database: DBT_LABS
    schema: RAW_SCHEMA
    tables:
      - name: raw_customer




# Default configurations for all your models
models:
  healthcare_dbt:                   # ← Must match your project name exactly!
    # Default materialization for all models (can be overridden per model)
    +materialized: view             # Start with views (fast to test), later change some to table/incremental
    
    # Default output schema in Snowflake
    staging:
      +database: appolo_hc
      +schema: staging              # → your staging models will go to APPOLO_HC.staging
      +materialized: view
      
    marts:
      +database: appolo_hc
      +schema: marts                # → final dimension/fact tables will go here
      +materialized: table