# models/sources.yml
version: 2

sources:
  - name: appolo_raw  # A logical name for your schema
    schema: RAW_SCH  # Your actual Snowflake schema
    database: APPOLO_HC #database in snowflake 
    tables:
      - name: appointment_raw
        description: Raw appointment data from S3
        columns:
          - name: appointment_id
            description: Unique appointment ID
          - name: patient_id
            description: Links to patient
          # Add the rest similarly...

      - name: department_raw
        description: Raw department data from S3
        columns:
          - name: department_id
            description: Unique department ID
          # Etc.

      - name: patient_raw
        description: Raw patient data from S3
        columns:
          - name: patient_id
            description: Unique patient ID
          - name: fullname
            description: Patient's full name
          - name: age
            description: Patient age (as text, needs casting)
          # Add all columns for completeness


  #   tables:
  # - name: patient_raw
  #   columns:
  #     - name: patient_id
  #       tests:
  #         - unique
  #         - not_null
  #     # - name: age
  #     #   tests:
  #     #     - dbt_utils.expression_is_true:
  #     #         expression: "try_to_number(age) between 0 and 120"  -- Basic validation