version: 2

models:
  - name: dim_patient
    columns:
      - name: patient_sk
        tests:
          - unique
          - not_null

  - name: dim_department
    columns:
      - name: department_sk
        tests:
          - unique
          - not_null

  - name: fact_appointment
    columns:
      - name: appointment_id
        tests:
          - unique
          - not_null
      - name: patient_sk
        tests:
          - not_null  # Ensures all appointments link to a patient
      - name: department_sk
        tests:
          - not_null